version: 2.1
jobs:
  deploy-gh-pages:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config --global user.name  "$GITHUB_USERNAME"
            git config --global user.email "$GITHUB_EMAI"
      - run:
          name: Deploying to GitHub Pages
          command: |
            echo "machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && yarn run publish-gh-pages
workflows:
  pipeline:
    jobs:
      - deploy-gh-pages:
          context: github
          filters:
            branches:
              only:
                - master
